<a href="https://colab.research.google.com/github/Mikhailo88/MN-Praktychni-K4/blob/main/%D0%9B%D0%A01_%D0%9E%D0%BB%D1%8C%D1%85%D0%BE%D0%B2%D0%B5%D0%BD%D0%BA%D0%BE_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE_%D0%A4%D0%86%D0%A2_4_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

## Підготовка

In [1]:
import numpy as np


## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [3]:
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * 4 =", a * 4)
print("b * (-2) =", b * (-2))
print("a * b =", a * b)

a + b = [10  4  4 13]
a - b = [ 4 -8  6  5]
a * 4 = [28 -8 20 36]
b * (-2) = [ -6 -12   2  -8]
a * b = [ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.

In [5]:
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])

dot1 = np.dot(u, v)
dot2 = u @ v

print("np.dot(u, v) =", dot1)
print("u @ v =", dot2)

norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

print("Норма u =", norm_u)
print("Норма v =", norm_v)

cos_angle = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

print("Косинус кута =", cos_angle)

np.dot(u, v) = 31
u @ v = 31
Норма u = 7.0
Норма v = 6.48074069840786
Косинус кута = 0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [7]:
A = np.array([
    [3, 5, -1],
    [2, 0, 4]
])

B = np.array([
    [1, -2, 6],
    [7, 3, 2]
])

print("A + B:")
print(A + B)

print("\nA - B:")
print(A - B)

print("\nA * B:")
print(A * B)

print("\nA * 5:")
print(A * 5)

print("\nТранспонована матриця A:")
print(A.T)

A + B:
[[4 3 5]
 [9 3 6]]

A - B:
[[ 2  7 -7]
 [-5 -3  2]]

A * B:
[[  3 -10  -6]
 [ 14   0   8]]

A * 5:
[[15 25 -5]
 [10  0 20]]

Транспонована матриця A:
[[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [8]:
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

C = A @ B

print("A @ B:")
print(C)

print("\nФорма результату:", C.shape)

manual = 2 * 2 + 1 * 0 + 3 * 1

print("\nЕлемент [0, 1] вручну:", manual)
print("Елемент C[0, 1]:", C[0, 1])

A @ B:
[[17  7]
 [32  5]]

Форма результату: (2, 2)

Елемент [0, 1] вручну: 7
Елемент C[0, 1]: 7


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [9]:
v = np.array([12, 7, 19, 4, 11, 8])

right = np.roll(v, 2)
print("Зсув на 2 вправо:", right)

left = np.roll(v, -3)
print("Зсув на 3 вліво:", left)

restored = np.roll(right, -2)
print("Відновлений вектор:", restored)

Зсув на 2 вправо: [11  8 12  7 19  4]
Зсув на 3 вліво: [ 4 11  8 12  7 19]
Відновлений вектор: [12  7 19  4 11  8]


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [10]:
v = np.array([42, 17, 29, 8, 35, 23])

ascending = np.sort(v)
print("За зростанням:", ascending)

descending = np.sort(v)[::-1]
print("За спаданням:", descending)

indices = np.argsort(v)[::-1]
print("Індекси:", indices)

За зростанням: [ 8 17 23 29 35 42]
За спаданням: [42 35 29 23 17  8]
Індекси: [0 4 2 5 1 3]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [11]:
v = np.array([-12, -4, 3, 18, 27, 35, 48])

clipped = np.clip(v, -5, 30)

print("Початковий вектор:", v)
print("Обмежений вектор:", clipped)

changed_indices = np.where(v != clipped)[0]

print("Індекси змінених елементів:", changed_indices)

Початковий вектор: [-12  -4   3  18  27  35  48]
Обмежений вектор: [-5 -4  3 18 27 30 30]
Індекси змінених елементів: [0 5 6]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [12]:
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

unique, counts = np.unique(v, return_counts=True)

print("Унікальні значення:", unique)
print("Кількість появ:", counts)

most_frequent = unique[np.argmax(counts)]

print("Найчастіше зустрічається:", most_frequent)

Унікальні значення: [2 4 7 9]
Кількість появ: [3 3 4 1]
Найчастіше зустрічається: 7


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [13]:
A = np.array([
    [2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

clockwise_90 = np.rot90(A, -1)
print("Поворот на 90° за годинниковою стрілкою:")
print(clockwise_90)

rotate_180 = np.rot90(A, 2)
print("\nПоворот на 180°:")
print(rotate_180)

counterclockwise_90 = np.rot90(A, 1)
print("\nПоворот на 90° проти годинникової стрілки:")
print(counterclockwise_90)

Поворот на 90° за годинниковою стрілкою:
[[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]

Поворот на 180°:
[[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]

Поворот на 90° проти годинникової стрілки:
[[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [14]:
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

frame_1 = np.pad(A, pad_width=1, mode='constant', constant_values=-1)

print("Рамка шириною 1 (-1):")
print(frame_1)

frame_2 = np.pad(A, pad_width=2, mode='constant', constant_values=0)

print("\nРамка шириною 2 (0):")
print(frame_2)

print("\nФорми матриць:")
print("Форма frame_1:", frame_1.shape)
print("Форма frame_2:", frame_2.shape)

Рамка шириною 1 (-1):
[[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]

Рамка шириною 2 (0):
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

Форми матриць:
Форма frame_1: (5, 5)
Форма frame_2: (7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [15]:
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

B = A[row_order]

print("Після перестановки рядків:")
print(B)

C = B[:, col_order]

print("\nПісля перестановки стовпців:")
print(C)

inv_row_order = np.argsort(row_order)
inv_col_order = np.argsort(col_order)

print("\nОбернена перестановка рядків:", inv_row_order)
print("Обернена перестановка стовпців:", inv_col_order)

D = C[:, inv_col_order]
D = D[inv_row_order]

print("\nВідновлена матриця:")
print(D)

Після перестановки рядків:
[[31 32 33 34]
 [11 12 13 14]
 [41 42 43 44]
 [21 22 23 24]]

Після перестановки стовпців:
[[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]

Обернена перестановка рядків: [1 3 0 2]
Обернена перестановка стовпців: [2 1 3 0]

Відновлена матриця:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [16]:
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

upper = np.triu(A)
print("Верхня трикутна частина:")
print(upper)

lower = np.tril(A)
print("\nНижня трикутна частина:")
print(lower)

strict_upper = np.triu(A, k=1)
strict_lower = np.tril(A, k=-1)

print("\nСтрого верхня частина:")
print(strict_upper)

print("\nСтрого нижня частина:")
print(strict_lower)

restored = lower + strict_upper

print("\nВідновлена матриця:")
print(restored)

Верхня трикутна частина:
[[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]

Нижня трикутна частина:
[[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]

Строго верхня частина:
[[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]

Строго нижня частина:
[[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]

Відновлена матриця:
[[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [17]:
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

C = np.outer(a, b)

print("Матриця зовнішнього добутку:")
print(C)

print("\nФорма матриці:", C.shape)

print("\nПеревірка елемента [2, 1]:")
print("C[2, 1] =", C[2, 1])
print("a[2] * b[1] =", a[2] * b[1])

Матриця зовнішнього добутку:
[[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]

Форма матриці: (4, 3)

Перевірка елемента [2, 1]:
C[2, 1] = 35
a[2] * b[1] = 35


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [19]:
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])

kron_AB = np.kron(A, B)

print("A x B:")
print(kron_AB)

kron_BA = np.kron(B, A)

print("\nB x A:")
print(kron_BA)

print("\nФорми матриць:")
print("Форма A x B:", kron_AB.shape)
print("Форма B x A:", kron_BA.shape)

print("\nОднакові?", np.array_equal(kron_AB, kron_BA))

A x B:
[[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]

B x A:
[[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]

Форми матриць:
Форма A x B: (4, 4)
Форма B x A: (4, 4)

Однакові? False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [21]:
A1 = np.array([
    [3, 0],
    [0, 7]
])

B1 = np.array([
    [2, 0],
    [0, 5]
])

A2 = np.array([
    [0, 2],
    [-1, 0]
])

B2 = np.array([
    [4, 0],
    [0, 1]
])

comm1 = A1 @ B1 - B1 @ A1
comm2 = A2 @ B2 - B2 @ A2

print("Комутатор першої пари [A1, B1]:")
print(comm1)

print("\nКомутатор другої пари [A2, B2]:")
print(comm2)

# Перевірка AB = BA
equal1 = np.allclose(A1 @ B1, B1 @ A1)
equal2 = np.allclose(A2 @ B2, B2 @ A2)

print("\nA1B1 = B1A1?", equal1)
print("A2B2 = B2A2?", equal2)

Комутатор першої пари [A1, B1]:
[[0 0]
 [0 0]]

Комутатор другої пари [A2, B2]:
[[ 0 -6]
 [-3  0]]

A1B1 = B1A1? True
A2B2 = B2A2? False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [24]:
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])

result = x.T @ A @ x

print("xᵀAx =", result)

X = np.array([
    [2, -1, 3],
    [1,  0, 2],
    [-2, 1, 1]
])

results = np.einsum('ij,jk,ik->i', X, A, X)

print("\nЗначення квадратичної форми для кожного вектора:")
print(results)

xᵀAx = 35

Значення квадратичної форми для кожного вектора:
[35 17 27]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [28]:
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

A2 = np.linalg.matrix_power(A, 2)
print("A²:")
print(A2)

A3 = np.linalg.matrix_power(A, 3)
print("\nA³:")
print(A3)

check = np.allclose(A3, A2 @ A)

print("\nA³ = A² @ A?")
print(check)

A²:
[[1 2 1]
 [1 1 2]
 [2 1 1]]

A³:
[[2 3 3]
 [3 2 3]
 [3 3 2]]

A³ = A² @ A?
True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [30]:
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

print("Ранг матриці A:", rank_A)
print("Ранг матриці B:", rank_B)

print("\nПовний ранг:")

if rank_A == min(A.shape):
    print("Матриця A має повний ранг")
else:
    print("Матриця A не має повного рангу")

if rank_B == min(B.shape):
    print("Матриця B має повний ранг")
else:
    print("Матриця B не має повного рангу")

Ранг матриці A: 3
Ранг матриці B: 2

Повний ранг:
Матриця A має повний ранг
Матриця B не має повного рангу


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [31]:
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

eigenvalues, V = np.linalg.eigh(A)

print("Власні значення:")
print(eigenvalues)

print("\nВласні вектори:")
print(V)

left = A @ V
right = V * eigenvalues

print("\nРезультат перевірки:")
print(np.allclose(left, right))

Власні значення:
[2. 7.]

Власні вектори:
[[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]

Результат перевірки:
True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [32]:
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

X = np.column_stack((np.ones(len(x)), x))

coefficients, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)
a, b = coefficients

y_pred = X @ coefficients

sum_squared_errors = np.sum((y - y_pred) ** 2)

print("Матриця ознак:")
print(X)

print("\nКоефіцієнт a =", a)
print("Коефіцієнт b =", b)

print("\nПрогнозні значення y:")
print(y_pred)

print("\nСума квадратів залишків =", sum_squared_errors)

Матриця ознак:
[[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]

Коефіцієнт a = 2.019999999999998
Коефіцієнт b = 2.0100000000000002

Прогнозні значення y:
[ 2.02  4.03  6.04  8.05 10.06]

Сума квадратів залишків = 0.13099999999999973
